### ISSUE TITLE
First code snippet shown is // Unsupported:

### ISSUE THREAD

**Issue by rektide** [mostjs/create#10]
The very first piece of code someone comes to starts with // Unsupported. It's also a think I believe many people will want to do.

README.md's first example should be a useful, good example.

**Comment by davidchase** [comment]
@rektide thanks for posting this issue, do you have any ideas how to make it better?

> The very first piece of code someone comes to starts with // Unsupported. 

I think its just referring that `most` or specifically `@most/create` does not support pulling functions outside of the closure. IOW just because it works, doesn't mean we encourage it.

But it does work:
http://www.webpackbin.com/E103bSQMf

> README.md's first example should be a useful, good example.

The 1st example is the one underneath [examples](https://github.com/mostjs/create#examples). The snippet you mention relates to the warning message above the actual snippet.

Nonetheless if you feel like there could be better wording and/or snippet please submit a PR.

**Comment by briancavalier** [comment]
Maybe it's as simple as moving the [examples](https://github.com/mostjs/create#examples) to the top of the README--for example, just after the [install](https://github.com/mostjs/create#install) section.  What do you think?

**Comment by briancavalier** [comment]
@rektide We moved the examples in #12.  If you feel like we can do more, feel free to reopen and give us some suggestions, or better yet, send a PR to improve things further.  Thanks!
